spring:
  application:
    name: zuul
  profiles:
    active: uat
  redis:
    host: 192.168.1.110
    port: 6379
    database: 0
    timeout: 30000
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    jyw-learn: /learn/**
    base-info: /baseinfo/**
    oauth: /oauth/**
  retryable: true
ribbon:
  ReadTimeout: 15000 #处理请求的超时时间，默认为10秒
  ConnectTimeout: 15000 #连接建立的超时时长，默认5秒
  MaxAutoRetries: 0               #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetriesNextServer: 0     #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  OkToRetryOnAllOperations: false #/是否对所有操作都重试，默认false
---
spring:
  profiles: local
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
    fetch-registry: true #拉取eureka注册信息
    register-with-eureka: true #
server:
  port: 8084
---
spring:
  profiles: uat
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
      #defaultZone: http://192.168.1.112:8082//eureka/,http://192.168.1.111:8082/eureka,http://192.168.1.110:8082/eureka #docker节点部署
      defaultZone: http://${EUREKA_SERVER_ADDR}:8082/eureka/ #docker swarm部署
    fetch-registry: true #拉取eureka注册信息
    register-with-eureka: true #
server:
  port: 8085